title: "From HK to SG"
email: fromhktosg@gmail.com
timezone: UTC
baseurl: ""
domain: fromhktosg.github.io
url: https://fromhktosg.github.io
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: David
paginate: 30
disqus: 'demowebsite'
locale: en_sg
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  David:
    name: 
    display_name: David
    avatar: 'assets/images/.png'
    email: fromhktosg@gmail.com
    web:
    description: "Welcome to From HK to SG."

# Social
social:
  instagram: https://www.instagram.com/fromhktosg/
  facebook: https://www.facebook.com/fromhktosg/
  twitter: https://twitter.com/fromhktosg

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives